# Generated by Django 5.0.6 on 2024-10-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiside', '0005_alter_plan_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersubscriptions',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
